version: '3.5'
services:
    db:
        image: mariadb
        restart: unless-stopped
        ports:
            - 3306:3306
        env_file: ../.env

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 9000:8080