version: '3.5'
services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        env_file: ../.env

    adminer:
        image: adminer
        restart: always
        ports:
            - 9000:8080